name: Stock Screener Alert Workflow

on:
  push:
    branches:
      - main

jobs:
  send_alert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install python-dotenv

    - name: Log Environment Variables
      run: |
        echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}"
        echo "CHAT_ID=${{ secrets.CHAT_ID }}"

    - name: Run Stock Screener and Send Alert
      run: |
        python screener.py
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}

    - name: Send Test Telegram Message
      run: |
        python -c 'import requests; requests.post("https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage", data={"chat_id": "${{ secrets.CHAT_ID }}", "text": "Test Alert!"})'
