name: Run Stock Screener Every 15 Minutes During NSE Trading Hours

on:
  schedule:
    - cron: '45,0,15,30,45 3-9 * * *'  # 9:15 AM to 3:30 PM IST
  workflow_dispatch:

jobs:
  run-screener:
    runs-on: ubuntu-latest

    env:  # <-- Add environment variables here
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Stock Screener
        run: python screener.py
